// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package cart

import (
	"context"
)

const addItemInCartChecked = `-- name: AddItemInCartChecked :execrows
INSERT INTO cart.users_carts (user_id, sku, amount)
VALUES ($1, $2, $3::bigint)
ON CONFLICT (user_id, sku) DO UPDATE
SET amount = cart.users_carts.amount + EXCLUDED.amount
WHERE cart.users_carts.amount + EXCLUDED.amount <= $4::bigint
`

type AddItemInCartCheckedParams struct {
	UserID int64 `json:"user_id"`
	Sku    int64 `json:"sku"`
	Amount int64 `json:"amount"`
	Stock  int64 `json:"stock"`
}

func (q *Queries) AddItemInCartChecked(ctx context.Context, arg AddItemInCartCheckedParams) (int64, error) {
	result, err := q.db.Exec(ctx, addItemInCartChecked,
		arg.UserID,
		arg.Sku,
		arg.Amount,
		arg.Stock,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearUserCart = `-- name: ClearUserCart :exec
DELETE
FROM cart.users_carts
WHERE user_id = $1
`

func (q *Queries) ClearUserCart(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, clearUserCart, userID)
	return err
}

const deleteItemFromCart = `-- name: DeleteItemFromCart :exec
DELETE
FROM cart.users_carts
WHERE user_id = $1
  AND sku = $2
`

type DeleteItemFromCartParams struct {
	UserID int64 `json:"user_id"`
	Sku    int64 `json:"sku"`
}

func (q *Queries) DeleteItemFromCart(ctx context.Context, arg DeleteItemFromCartParams) error {
	_, err := q.db.Exec(ctx, deleteItemFromCart, arg.UserID, arg.Sku)
	return err
}

const getItemCountInCart = `-- name: GetItemCountInCart :one
SELECT COALESCE(
               (SELECT amount
                FROM cart.users_carts
                WHERE user_id = $1
                  AND sku = $2),
               0
       )::bigint AS amount
`

type GetItemCountInCartParams struct {
	UserID int64 `json:"user_id"`
	Sku    int64 `json:"sku"`
}

func (q *Queries) GetItemCountInCart(ctx context.Context, arg GetItemCountInCartParams) (int64, error) {
	row := q.db.QueryRow(ctx, getItemCountInCart, arg.UserID, arg.Sku)
	var amount int64
	err := row.Scan(&amount)
	return amount, err
}

const getUserCart = `-- name: GetUserCart :many
SELECT sku, amount
FROM cart.users_carts
WHERE user_id = $1
`

type GetUserCartRow struct {
	Sku    int64 `json:"sku"`
	Amount int64 `json:"amount"`
}

func (q *Queries) GetUserCart(ctx context.Context, userID int64) ([]GetUserCartRow, error) {
	rows, err := q.db.Query(ctx, getUserCart, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserCartRow
	for rows.Next() {
		var i GetUserCartRow
		if err := rows.Scan(&i.Sku, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserCartForUpdate = `-- name: GetUserCartForUpdate :many
SELECT sku, amount
FROM cart.users_carts
WHERE user_id = $1
FOR UPDATE
`

type GetUserCartForUpdateRow struct {
	Sku    int64 `json:"sku"`
	Amount int64 `json:"amount"`
}

func (q *Queries) GetUserCartForUpdate(ctx context.Context, userID int64) ([]GetUserCartForUpdateRow, error) {
	rows, err := q.db.Query(ctx, getUserCartForUpdate, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserCartForUpdateRow
	for rows.Next() {
		var i GetUserCartForUpdateRow
		if err := rows.Scan(&i.Sku, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
