// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package cart

import (
	"context"
)

type Querier interface {
	AddItemInCartChecked(ctx context.Context, arg AddItemInCartCheckedParams) (int64, error)
	ClearUserCart(ctx context.Context, userID int64) error
	DeleteItemFromCart(ctx context.Context, arg DeleteItemFromCartParams) error
	GetItemCountInCart(ctx context.Context, arg GetItemCountInCartParams) (int64, error)
	GetUserCart(ctx context.Context, userID int64) ([]GetUserCartRow, error)
	GetUserCartForUpdate(ctx context.Context, userID int64) ([]GetUserCartForUpdateRow, error)
}

var _ Querier = (*Queries)(nil)
