services:
  cart:
    image: cart
    hostname: cart
    build:
      context: .
      dockerfile: ./cart/Dockerfile
    restart: unless-stopped
    environment:
      GRPC_PORT: "50051"
      GRPC_GATEWAY_PORT: "8080"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "ecommerce"
      POSTGRES_USER: "ecommerce_user"
      POSTGRES_PASSWORD: "12345"
      LOMS_GRPC_ADDR: "loms:50052"
    depends_on:
      postgres:
        condition: service_healthy
      loms:
        condition: service_started
    ports:
      - "8080:8080"
      - "50051:50051"

  cart-2:
    image: cart
    hostname: cart-2
    build:
      context: .
      dockerfile: ./cart/Dockerfile
    restart: unless-stopped
    environment:
      GRPC_PORT: "50061"
      GRPC_GATEWAY_PORT: "8090"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "ecommerce"
      POSTGRES_USER: "ecommerce_user"
      POSTGRES_PASSWORD: "12345"
      LOMS_GRPC_ADDR: "loms-2:50062"
    depends_on:
      postgres:
        condition: service_healthy
      loms-2:
        condition: service_started
      cart:
        condition: service_started
    ports:
      - "8090:8090"
      - "50061:50061"

  loms:
    image: loms
    hostname: loms
    build:
      context: .
      dockerfile: ./loms/Dockerfile
    restart: unless-stopped
    environment:
      GRPC_PORT: "50052"
      GRPC_GATEWAY_PORT: "8081"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "ecommerce"
      POSTGRES_USER: "ecommerce_user"
      POSTGRES_PASSWORD: "12345"
      OUTBOX_WORKERS: "1"
      OUTBOX_BATCH_SIZE: "10"
      OUTBOX_FETCH_PERIOD: "200ms"
      OUTBOX_IN_PROGRESS_TTL: "1s"
      KAFKA_BROKERS: "kafka-single:9092"
      KAFKA_NOTIFICATIONS_TOPIC: "order_status_notifications"
    depends_on:
      postgres:
        condition: service_healthy
      notifications:
        condition: service_started
      kafka-single:
        condition: service_healthy
    ports:
      - "50052:50052"
      - "8081:8081"

  loms-2:
    image: loms
    hostname: loms-2
    build:
      context: .
      dockerfile: ./loms/Dockerfile
    restart: unless-stopped
    environment:
      GRPC_PORT: "50062"
      GRPC_GATEWAY_PORT: "8091"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "ecommerce"
      POSTGRES_USER: "ecommerce_user"
      POSTGRES_PASSWORD: "12345"
      OUTBOX_WORKERS: "1"
      OUTBOX_BATCH_SIZE: "10"
      OUTBOX_FETCH_PERIOD: "200ms"
      OUTBOX_IN_PROGRESS_TTL: "1s"
      KAFKA_BROKERS: "kafka-single:9092"
      KAFKA_NOTIFICATIONS_TOPIC: "order_status_notifications"
    depends_on:
      postgres:
        condition: service_healthy
      notifications:
        condition: service_started
      loms:
        condition: service_started
      kafka-single:
        condition: service_healthy
    ports:
      - "50062:50062"
      - "8091:8091"

  notifications:
    image: notifications
    hostname: notifications
    build:
      context: .
      dockerfile: ./notifications/Dockerfile
    restart: unless-stopped
    environment:
      CALLBACK_ADDR: ""
      GRPC_PORT: "50053"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "ecommerce"
      POSTGRES_USER: "ecommerce_user"
      POSTGRES_PASSWORD: "12345"
      KAFKA_BROKERS: "kafka-single:9092"
      KAFKA_NOTIFICATIONS_TOPIC: "order_status_notifications"
      KAFKA_CONSUMER_GROUP: "notifications"
    depends_on:
      kafka-single:
        condition: service_healthy
    ports:
      - "50053:50053"

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: "ecommerce"
      POSTGRES_USER: "ecommerce_user"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_PORT: "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "port=5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ecommerce_user -d ecommerce" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-single:
    image: confluentinc/cp-kafka:7.6.1
    hostname: kafka-single
    container_name: kafka-single
    ports:
      - "9092:9092"
      - "9093:9094"
      - "9101:9101"
    environment:
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: "PLAINTEXT://kafka-single:9092,CONTROLLER://kafka-single:9093,PLAINTEXT_HOST://0.0.0.0:9094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-single:9092,PLAINTEXT_HOST://localhost:9093"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-single:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_NUM_PARTITIONS: 2
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server kafka-single:9092 >/dev/null 2>&1" ]
      interval: 10s
      timeout: 5s
      retries: 10

  kafdrop:
    image: obsidiandynamics/kafdrop:4.0.1
    container_name: kafdrop-single
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka-single:9092"
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXT_PATH: "/"
    depends_on:
      kafka-single:
        condition: service_healthy

volumes:
  postgres-data:
