// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package product

import (
	"context"
)

type Querier interface {
	AddProduct(ctx context.Context, arg AddProductParams) (int64, error)
	GetProductBySKU(ctx context.Context, sku int64) (GetProductBySKURow, error)
}

var _ Querier = (*Queries)(nil)
