// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package product

import (
	"context"
)

const addProduct = `-- name: AddProduct :one
INSERT INTO loms.products (name, price)
VALUES ($1, $2) RETURNING sku
`

type AddProductParams struct {
	Name  string `json:"name"`
	Price int64  `json:"price"`
}

func (q *Queries) AddProduct(ctx context.Context, arg AddProductParams) (int64, error) {
	row := q.db.QueryRow(ctx, addProduct, arg.Name, arg.Price)
	var sku int64
	err := row.Scan(&sku)
	return sku, err
}

const getProductBySKU = `-- name: GetProductBySKU :one
SELECT name, price
FROM loms.products
WHERE sku = $1
`

type GetProductBySKURow struct {
	Name  string `json:"name"`
	Price int64  `json:"price"`
}

func (q *Queries) GetProductBySKU(ctx context.Context, sku int64) (GetProductBySKURow, error) {
	row := q.db.QueryRow(ctx, getProductBySKU, sku)
	var i GetProductBySKURow
	err := row.Scan(&i.Name, &i.Price)
	return i, err
}
