// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package outbox

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOutboxMessage = `-- name: AddOutboxMessage :exec
INSERT INTO loms.outbox (idempotency_key, data, status, kind)
VALUES (
           $1,
           $2,
           'CREATED'::outbox_status,
           $3
       )
ON CONFLICT (idempotency_key) DO NOTHING
`

type AddOutboxMessageParams struct {
	IdempotencyKey string `json:"idempotency_key"`
	Data           []byte `json:"data"`
	Kind           int32  `json:"kind"`
}

func (q *Queries) AddOutboxMessage(ctx context.Context, arg AddOutboxMessageParams) error {
	_, err := q.db.Exec(ctx, addOutboxMessage, arg.IdempotencyKey, arg.Data, arg.Kind)
	return err
}

const getOutboxMessages = `-- name: GetOutboxMessages :many
UPDATE loms.outbox
SET status = 'IN_PROGRESS'::outbox_status
WHERE idempotency_key IN (
    SELECT idempotency_key
    FROM loms.outbox
    WHERE
        status = 'CREATED'::outbox_status
       OR (
        status = 'IN_PROGRESS'::outbox_status
          AND updated_at < now() - $1::interval
        )
    ORDER BY created_at
    LIMIT $2
        FOR UPDATE SKIP LOCKED
)
RETURNING idempotency_key, data, kind
`

type GetOutboxMessagesParams struct {
	InProgressTtl pgtype.Interval `json:"in_progress_ttl"`
	BatchSize     int32           `json:"batch_size"`
}

type GetOutboxMessagesRow struct {
	IdempotencyKey string `json:"idempotency_key"`
	Data           []byte `json:"data"`
	Kind           int32  `json:"kind"`
}

func (q *Queries) GetOutboxMessages(ctx context.Context, arg GetOutboxMessagesParams) ([]GetOutboxMessagesRow, error) {
	rows, err := q.db.Query(ctx, getOutboxMessages, arg.InProgressTtl, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOutboxMessagesRow
	for rows.Next() {
		var i GetOutboxMessagesRow
		if err := rows.Scan(&i.IdempotencyKey, &i.Data, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxMessagesAsProcessed = `-- name: MarkOutboxMessagesAsProcessed :exec
UPDATE loms.outbox
SET status = 'SUCCESS'::outbox_status
WHERE idempotency_key = ANY($1::text[])
`

func (q *Queries) MarkOutboxMessagesAsProcessed(ctx context.Context, idempotencyKeys []string) error {
	_, err := q.db.Exec(ctx, markOutboxMessagesAsProcessed, idempotencyKeys)
	return err
}

const markOutboxMessagesAsRetryable = `-- name: MarkOutboxMessagesAsRetryable :exec
UPDATE loms.outbox
SET status = 'CREATED'::outbox_status
WHERE idempotency_key = ANY($1::text[])
`

func (q *Queries) MarkOutboxMessagesAsRetryable(ctx context.Context, idempotencyKeys []string) error {
	_, err := q.db.Exec(ctx, markOutboxMessagesAsRetryable, idempotencyKeys)
	return err
}
