// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package outbox

import (
	"context"
)

type Querier interface {
	AddOutboxMessage(ctx context.Context, arg AddOutboxMessageParams) error
	GetOutboxMessages(ctx context.Context, arg GetOutboxMessagesParams) ([]GetOutboxMessagesRow, error)
	MarkOutboxMessagesAsProcessed(ctx context.Context, idempotencyKeys []string) error
	MarkOutboxMessagesAsRetryable(ctx context.Context, idempotencyKeys []string) error
}

var _ Querier = (*Queries)(nil)
