// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package order

import (
	"context"
)

type Querier interface {
	AddOrder(ctx context.Context, arg AddOrderParams) (int64, error)
	AddOrderInfo(ctx context.Context, arg AddOrderInfoParams) error
	GetOrder(ctx context.Context, id int64) (LomsOrder, error)
	GetOrderForUpdate(ctx context.Context, id int64) (LomsOrder, error)
	GetOrderItems(ctx context.Context, orderID int64) ([]GetOrderItemsRow, error)
	GetOrderStatus(ctx context.Context, id int64) (LomsOrderStatus, error)
	SwapOrderStatus(ctx context.Context, arg SwapOrderStatusParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
