// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package order

import (
	"context"
)

const addOrder = `-- name: AddOrder :one
INSERT INTO loms.orders (user_id, status)
VALUES ($1, $2)
RETURNING id
`

type AddOrderParams struct {
	UserID int64           `json:"user_id"`
	Status LomsOrderStatus `json:"status"`
}

func (q *Queries) AddOrder(ctx context.Context, arg AddOrderParams) (int64, error) {
	row := q.db.QueryRow(ctx, addOrder, arg.UserID, arg.Status)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const addOrderInfo = `-- name: AddOrderInfo :exec
INSERT INTO loms.order_info (order_id, sku, amount)
VALUES ($1, $2, $3)
ON CONFLICT (order_id, sku) DO UPDATE
    SET amount = loms.order_info.amount + EXCLUDED.amount
`

type AddOrderInfoParams struct {
	OrderID int64 `json:"order_id"`
	Sku     int64 `json:"sku"`
	Amount  int64 `json:"amount"`
}

func (q *Queries) AddOrderInfo(ctx context.Context, arg AddOrderInfoParams) error {
	_, err := q.db.Exec(ctx, addOrderInfo, arg.OrderID, arg.Sku, arg.Amount)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, status, created_at, updated_at
FROM loms.orders
WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (LomsOrder, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i LomsOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderForUpdate = `-- name: GetOrderForUpdate :one
SELECT id, user_id, status, created_at, updated_at
FROM loms.orders
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetOrderForUpdate(ctx context.Context, id int64) (LomsOrder, error) {
	row := q.db.QueryRow(ctx, getOrderForUpdate, id)
	var i LomsOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT sku, amount
FROM loms.order_info
WHERE order_id = $1
`

type GetOrderItemsRow struct {
	Sku    int64 `json:"sku"`
	Amount int64 `json:"amount"`
}

func (q *Queries) GetOrderItems(ctx context.Context, orderID int64) ([]GetOrderItemsRow, error) {
	rows, err := q.db.Query(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsRow
	for rows.Next() {
		var i GetOrderItemsRow
		if err := rows.Scan(&i.Sku, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderStatus = `-- name: GetOrderStatus :one
SELECT status
FROM loms.orders
WHERE id = $1
`

func (q *Queries) GetOrderStatus(ctx context.Context, id int64) (LomsOrderStatus, error) {
	row := q.db.QueryRow(ctx, getOrderStatus, id)
	var status LomsOrderStatus
	err := row.Scan(&status)
	return status, err
}

const swapOrderStatus = `-- name: SwapOrderStatus :execrows
UPDATE loms.orders
SET status = $3
WHERE id = $1
  AND status = $2
`

type SwapOrderStatusParams struct {
	ID       int64           `json:"id"`
	Status   LomsOrderStatus `json:"status"`
	Status_2 LomsOrderStatus `json:"status_2"`
}

func (q *Queries) SwapOrderStatus(ctx context.Context, arg SwapOrderStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, swapOrderStatus, arg.ID, arg.Status, arg.Status_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
