// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package stocks

import (
	"context"
)

const addAvailableStock = `-- name: AddAvailableStock :exec
INSERT INTO loms.available_stocks (sku, amount)
VALUES ($1, $2) ON CONFLICT (sku) DO
UPDATE SET amount = loms.available_stocks.amount + EXCLUDED.amount
`

type AddAvailableStockParams struct {
	Sku    int64 `json:"sku"`
	Amount int64 `json:"amount"`
}

func (q *Queries) AddAvailableStock(ctx context.Context, arg AddAvailableStockParams) error {
	_, err := q.db.Exec(ctx, addAvailableStock, arg.Sku, arg.Amount)
	return err
}

const addReserveStock = `-- name: AddReserveStock :exec
INSERT INTO loms.reserved_stocks (sku, order_id, amount)
VALUES ($1, $2, $3) ON CONFLICT (sku, order_id) DO
UPDATE SET amount = loms.reserved_stocks.amount + EXCLUDED.amount
`

type AddReserveStockParams struct {
	Sku     int64 `json:"sku"`
	OrderID int64 `json:"order_id"`
	Amount  int64 `json:"amount"`
}

func (q *Queries) AddReserveStock(ctx context.Context, arg AddReserveStockParams) error {
	_, err := q.db.Exec(ctx, addReserveStock, arg.Sku, arg.OrderID, arg.Amount)
	return err
}

const decrementAvailableStock = `-- name: DecrementAvailableStock :execrows
UPDATE loms.available_stocks
SET amount = amount - $2
WHERE sku = $1
  AND amount >= $2
`

type DecrementAvailableStockParams struct {
	Sku    int64 `json:"sku"`
	Amount int64 `json:"amount"`
}

func (q *Queries) DecrementAvailableStock(ctx context.Context, arg DecrementAvailableStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, decrementAvailableStock, arg.Sku, arg.Amount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const decrementReservedStock = `-- name: DecrementReservedStock :execrows
UPDATE loms.reserved_stocks
SET amount = amount - $3
WHERE sku = $1
  AND order_id = $2
  and amount >= $3
`

type DecrementReservedStockParams struct {
	Sku     int64 `json:"sku"`
	OrderID int64 `json:"order_id"`
	Amount  int64 `json:"amount"`
}

func (q *Queries) DecrementReservedStock(ctx context.Context, arg DecrementReservedStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, decrementReservedStock, arg.Sku, arg.OrderID, arg.Amount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAvailableStock = `-- name: GetAvailableStock :one
SELECT COALESCE(loms.available_stocks.amount, 0) ::bigint AS amount
FROM loms.available_stocks
WHERE loms.available_stocks.sku = $1
`

func (q *Queries) GetAvailableStock(ctx context.Context, sku int64) (int64, error) {
	row := q.db.QueryRow(ctx, getAvailableStock, sku)
	var amount int64
	err := row.Scan(&amount)
	return amount, err
}

const setAvailableStock = `-- name: SetAvailableStock :execrows
INSERT INTO loms.available_stocks (sku, amount)
SELECT loms.products.sku, $2
FROM loms.products
WHERE loms.products.sku = $1 ON CONFLICT (sku) DO
UPDATE SET amount = EXCLUDED.amount
`

type SetAvailableStockParams struct {
	Sku    int64 `json:"sku"`
	Amount int64 `json:"amount"`
}

func (q *Queries) SetAvailableStock(ctx context.Context, arg SetAvailableStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAvailableStock, arg.Sku, arg.Amount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
