// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package stocks

import (
	"context"
)

type Querier interface {
	AddAvailableStock(ctx context.Context, arg AddAvailableStockParams) error
	AddReserveStock(ctx context.Context, arg AddReserveStockParams) error
	DecrementAvailableStock(ctx context.Context, arg DecrementAvailableStockParams) (int64, error)
	DecrementReservedStock(ctx context.Context, arg DecrementReservedStockParams) (int64, error)
	GetAvailableStock(ctx context.Context, sku int64) (int64, error)
	SetAvailableStock(ctx context.Context, arg SetAvailableStockParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
