// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package inbox

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addDeadInboxMessage = `-- name: AddDeadInboxMessage :exec
INSERT INTO notifications.inbox (
    idempotency_key,
    data,
    status,
    kafka_topic,
    kafka_partition,
    kafka_offset,
    attempts,
    last_error,
    dead_at
)
VALUES (
           $1,
           $2,
           'DEAD'::inbox_status,
           $3,
           $4,
           $5,
           0,
           $6::text,
           now()
       )
ON CONFLICT DO NOTHING
`

type AddDeadInboxMessageParams struct {
	IdempotencyKey string `json:"idempotency_key"`
	Data           []byte `json:"data"`
	KafkaTopic     string `json:"kafka_topic"`
	KafkaPartition int32  `json:"kafka_partition"`
	KafkaOffset    int64  `json:"kafka_offset"`
	LastError      string `json:"last_error"`
}

func (q *Queries) AddDeadInboxMessage(ctx context.Context, arg AddDeadInboxMessageParams) error {
	_, err := q.db.Exec(ctx, addDeadInboxMessage,
		arg.IdempotencyKey,
		arg.Data,
		arg.KafkaTopic,
		arg.KafkaPartition,
		arg.KafkaOffset,
		arg.LastError,
	)
	return err
}

const addInboxMessage = `-- name: AddInboxMessage :exec
INSERT INTO notifications.inbox (idempotency_key, data, kafka_topic, kafka_partition, kafka_offset)
VALUES (
           $1,
           $2,
           $3,
           $4,
           $5
       )
ON CONFLICT DO NOTHING
`

type AddInboxMessageParams struct {
	IdempotencyKey string `json:"idempotency_key"`
	Data           []byte `json:"data"`
	KafkaTopic     string `json:"kafka_topic"`
	KafkaPartition int32  `json:"kafka_partition"`
	KafkaOffset    int64  `json:"kafka_offset"`
}

func (q *Queries) AddInboxMessage(ctx context.Context, arg AddInboxMessageParams) error {
	_, err := q.db.Exec(ctx, addInboxMessage,
		arg.IdempotencyKey,
		arg.Data,
		arg.KafkaTopic,
		arg.KafkaPartition,
		arg.KafkaOffset,
	)
	return err
}

const getInboxMessages = `-- name: GetInboxMessages :many
WITH picked AS (
    SELECT i.idempotency_key
    FROM notifications.inbox AS i
    WHERE
        i.attempts < $1
      AND (
        i.status = 'CREATED'::inbox_status
            OR (
                i.status = 'RETRYABLE'::inbox_status
                AND i.next_retry_at <= now()
            )
            OR (
                i.status = 'IN_PROGRESS'::inbox_status
                AND i.updated_at < now() - $2::interval
            )
        )
    ORDER BY i.created_at
    LIMIT $3
    FOR UPDATE SKIP LOCKED
            )
UPDATE notifications.inbox AS i
SET
    status = 'IN_PROGRESS'::inbox_status,
    attempts = i.attempts + 1
FROM picked
WHERE i.idempotency_key = picked.idempotency_key
    RETURNING i.idempotency_key, i.data
`

type GetInboxMessagesParams struct {
	MaxAttempts   int32           `json:"max_attempts"`
	InProgressTtl pgtype.Interval `json:"in_progress_ttl"`
	BatchSize     int32           `json:"batch_size"`
}

type GetInboxMessagesRow struct {
	IdempotencyKey string `json:"idempotency_key"`
	Data           []byte `json:"data"`
}

func (q *Queries) GetInboxMessages(ctx context.Context, arg GetInboxMessagesParams) ([]GetInboxMessagesRow, error) {
	rows, err := q.db.Query(ctx, getInboxMessages, arg.MaxAttempts, arg.InProgressTtl, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInboxMessagesRow
	for rows.Next() {
		var i GetInboxMessagesRow
		if err := rows.Scan(&i.IdempotencyKey, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInboxMessagesAsFailed = `-- name: MarkInboxMessagesAsFailed :exec
UPDATE notifications.inbox
SET
    status = CASE
        WHEN attempts >= $1
            THEN 'DEAD'::inbox_status
        ELSE 'RETRYABLE'::inbox_status
    END,
    last_error = $2::text,
    dead_at = CASE
        WHEN attempts >= $1
            THEN now()
        ELSE dead_at
    END,
    next_retry_at = CASE
        WHEN attempts >= $1
            THEN next_retry_at
        ELSE now() + $3::interval
    END
WHERE idempotency_key = $4::text
    AND status = 'IN_PROGRESS'::inbox_status
`

type MarkInboxMessagesAsFailedParams struct {
	MaxAttempts    int32           `json:"max_attempts"`
	LastError      string          `json:"last_error"`
	RetryDelay     pgtype.Interval `json:"retry_delay"`
	IdempotencyKey string          `json:"idempotency_key"`
}

func (q *Queries) MarkInboxMessagesAsFailed(ctx context.Context, arg MarkInboxMessagesAsFailedParams) error {
	_, err := q.db.Exec(ctx, markInboxMessagesAsFailed,
		arg.MaxAttempts,
		arg.LastError,
		arg.RetryDelay,
		arg.IdempotencyKey,
	)
	return err
}

const markInboxMessagesAsSuccess = `-- name: MarkInboxMessagesAsSuccess :exec
UPDATE notifications.inbox
SET status = 'SUCCESS'::inbox_status
WHERE idempotency_key = ANY ($1::text[])
    AND status = 'IN_PROGRESS'::inbox_status
`

func (q *Queries) MarkInboxMessagesAsSuccess(ctx context.Context, idempotencyKeys []string) error {
	_, err := q.db.Exec(ctx, markInboxMessagesAsSuccess, idempotencyKeys)
	return err
}
