// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package inbox

import (
	"context"
)

type Querier interface {
	AddDeadInboxMessage(ctx context.Context, arg AddDeadInboxMessageParams) error
	AddInboxMessage(ctx context.Context, arg AddInboxMessageParams) error
	GetInboxMessages(ctx context.Context, arg GetInboxMessagesParams) ([]GetInboxMessagesRow, error)
	MarkInboxMessagesAsFailed(ctx context.Context, arg MarkInboxMessagesAsFailedParams) error
	MarkInboxMessagesAsSuccess(ctx context.Context, idempotencyKeys []string) error
}

var _ Querier = (*Queries)(nil)
