-- +goose Up
-- +goose StatementBegin
CREATE TYPE loms.order_status AS ENUM ('new', 'awaiting_payment', 'failed', 'paid', 'cancelled', 'unavailable');

CREATE TABLE loms.orders
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT                  NOT NULL,
    status     loms.order_status       NOT NULL,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE TABLE loms.order_info
(
    order_id BIGINT NOT NULL REFERENCES loms.orders (id) ON DELETE CASCADE,
    sku      BIGINT NOT NULL REFERENCES loms.products (sku),
    amount   BIGINT NOT NULL CHECK (amount > 0),

    PRIMARY KEY (order_id, sku)
);
-- +goose StatementEnd

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION update_loms_orders_timestamp() RETURNS TRIGGER AS
$$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- +goose StatementEnd

CREATE OR REPLACE TRIGGER trigger_update_loms_orders_timestamp
    BEFORE UPDATE
    ON loms.orders
    FOR EACH ROW
EXECUTE FUNCTION update_loms_orders_timestamp();

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS trigger_update_outbox_timestamp ON loms.outbox;
DROP FUNCTION IF EXISTS update_outbox_timestamp;
DROP TABLE IF EXISTS loms.order_info;
DROP TABLE IF EXISTS loms.orders;
DROP TYPE IF EXISTS loms.order_status;
-- +goose StatementEnd
