-- +goose Up
-- +goose StatementBegin
CREATE SCHEMA IF NOT EXISTS loms;

CREATE TABLE loms.products
(
    sku   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  TEXT   NOT NULL,
    price BIGINT NOT NULL CHECK (price > 0)
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS loms.products;
-- +goose StatementEnd
